# This file is part of the Openjet package.
# (c) Openjet SA

doctrine_migrations:
    dir_name:   '%kernel.project_dir%/app/migrations'
    namespace:  Migrations
    table_name: migrations
    name:       Migrations
